ProyectoFinalCerveceria/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinalCerveceria.Data;
using ProyectoFinalCerveceria.Models;

namespace ProyectoFinalCerveceria.Controllers
{
    public class CustomersController : Controller
    {
        private BeerContext db = new BeerContext();

        // GET: Customers
        public ActionResult Index()
        {
            var customers = db.Customers.Include(c => c.DocumentType);
            return View(customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            var list = db.DocumentTypes.ToList();
            list.Add(new DocumentType { DocumentTypeId = 0, Description = "- Seleccione -" });
            list = list.OrderBy(c => c.Description).ToList();
            ViewBag.DocumentTypeId = new SelectList(list, "DocumentTypeId", "Description");
            return View();
        }

        // POST: Customers/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerId,Identification,Name,LastName,Address,Email,PhoneNumber,DocumentTypeId")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DocumentTypeId = new SelectList(db.DocumentTypes, "DocumentTypeId", "Description", customer.DocumentTypeId);
            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.DocumentTypeId = new SelectList(db.DocumentTypes, "DocumentTypeId", "Description", customer.DocumentTypeId);
            return View(customer);
        }

        // POST: Customers/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerId,Identification,Name,LastName,Address,Email,PhoneNumber,DocumentTypeId")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DocumentTypeId = new SelectList(db.DocumentTypes, "DocumentTypeId", "Description", customer.DocumentTypeId);
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinalCerveceria/Controllers/OrdersController.cs
using ProyectoFinalCerveceria.Data;
using ProyectoFinalCerveceria.Models;
using ProyectoFinalCerveceria.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoFinalCerveceria.Controllers
{
    public class OrdersController : Controller
    {
        private BeerContext db = new BeerContext();
        public ActionResult NewOrder()
        {
            var orderView = new OrderView();
            cargarView(orderView);
            cargarCustomer();
            return View(orderView);
        }

        [HttpPost]
        public ActionResult NewOrder(OrderView orderView)
        {
            orderView = Session["orderView"] as OrderView;
            var customerId = int.Parse(Request["CustomerId"]);
            if (customerId == 0)
            {
                cargarCustomer();
                ViewBag.Error = "Debe seleccionar un cliente";
                return View(orderView);
            }
            var customer = db.Customers.Find(customerId);
            if (customer == null)
            {
                cargarCustomer();
                ViewBag.Error = "Cliente no existe";
                return View(orderView);
            }
            if(orderView.Products.Count == 0)
            {
                cargarCustomer();
                ViewBag.Error = "Debe ingresar detalles";
                return View(orderView);
            }

            int orderId = 0;

            using(var transaction = db.Database.BeginTransaction()) {
                try {
                    var order = new Order
                    {
                        CustomerId = customerId,
                        DateOrder = DateTime.Now,
                        OrderSatus = OrderSatus.Creado
                    };

                    db.Orders.Add(order);
                    db.SaveChanges();

                    orderId = db.Orders.ToList().Select(o => o.OrderID).Max();
                    foreach (var item in orderView.Products)
                    {
                        var orderDetail = new OrderDetail
                        {
                            ProductId = item.ProductId,
                            description = item.ProductName,
                            Price = item.Price,
                            Quantity = item.Quantity,
                            OrderID = orderId
                        };
                        db.OrderDetails.Add(orderDetail);
                        db.SaveChanges();
                    }
                    transaction.Commit();
                } catch (Exception ex)
                {
                    transaction.Rollback();
                    ViewBag.Error = "ERROR: " + ex.Message;
                    cargarCustomer();
                    return View(orderView);
                }
            
            }

            ViewBag.Message = string.Format("La orden:{0} guardada",orderId);
            cargarCustomer();
            cargarView(orderView);
            return View(orderView);
        }

        public ActionResult AddProduct()
        {
            cargarProduct();
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(ProductOrder productOrder)
        {
            var orderView = Session["orderView"] as OrderView;

            var productId = int.Parse(Request["ProductId"]);
            if (productId == 0)
            {
                cargarProduct();
                ViewBag.Error = "Debe seleccionar un producto";
                return View(productOrder);
            }

            var product = db.Products.Find(productId);
            if(product == null)
            {
                cargarProduct();
                ViewBag.Error = "Producto no existe";
                return View(productOrder);
            }
            productOrder = orderView.Products.Find(p => p.ProductId == productId);
            if(productOrder == null) { 
            productOrder = new ProductOrder
            {
                ProductName = product.ProductName,
                Price = product.Price,
                ProductId = product.ProductId,
                Quantity = float.Parse(Request["Quantity"])

            };
                orderView.Products.Add(productOrder);
            }
            else
            {
                productOrder.Quantity += float.Parse(Request["Quantity"]);
            }
           
            cargarCustomer();
            return View("NewOrder",orderView);
        }
        private void cargarCustomer()
        {
            var list = db.Customers.ToList();
            list.Add(new Customer { CustomerId = 0, Name = "- Seleccione", LastName = " un cliente -" });
            list = list.OrderBy(c => c.FullName).ToList();
            ViewBag.CustomerId = new SelectList(list, "CustomerId", "FullName");
        }

        private void cargarProduct()
        {
            var list = db.Products.ToList();
            list.Add(new Product { ProductId = 0, ProductName = "- Seleccione un producto -" });
            list = list.OrderBy(p => p.ProductName).ToList();
            ViewBag.ProductId = new SelectList(list, "ProductId", "ProductName");
        }

        private void cargarView(OrderView orderView)
        {
            orderView.Customer = new Customer();
            orderView.Products = new List<ProductOrder>();
            Session["orderView"] = orderView;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinalCerveceria/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using ProyectoFinalCerveceria.Data;
using ProyectoFinalCerveceria.Models;

namespace ProyectoFinalCerveceria.Controllers
{
    public class ProductsController : Controller
    {
        private BeerContext db = new BeerContext();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        public ActionResult CatalogProduct()
        {
            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ProductCode,ProductName,Price,Stock,Image")] Product product)
        {
            HttpPostedFileBase http = Request.Files[0];
            WebImage webImage = new WebImage(http.InputStream);
            product.Image = webImage.GetBytes();
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductCode,ProductName,Price,Stock,Image")] Product product)
        {
            HttpPostedFileBase http = Request.Files[0];
            WebImage webImage = new WebImage(http.InputStream);
            product.Image = webImage.GetBytes();
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinalCerveceria/Views/Shared/_CaruselPartial.cshtml
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img class="first-slide" src="~/img/file-1.jpg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Bienvenidos!</h1>
                    <p>Es un placer conocerte</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Conocer más</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img class="second-slide" src="~/img/file-2.jpg" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Descubre</h1>
                    <p>Descubre nuevas sensaciones con la cerveza artesanal! Encuentra tus estilos favoritos, vive la revolución cervecera en Ecuador.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Conocer más</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img class="third-slide" src="~/img/file-3.jpg" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Somos</h1>
                    <p>Cerveceros Artesanales independientes. Buscamos promover la Cerveza Artesanal Ecuatoriana de calidad</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Conocer más</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

ProyectoFinalCerveceria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar-wrapper">
        <div class="container">

            <nav class="navbar navbar-inverse navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Beer Time", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                            <li>@Html.ActionLink("Quienes Somos", "About", "Home")</li>
                            <li>@Html.ActionLink("Productos", "CatalogProduct", "Products")</li>
                            <li>@Html.ActionLink("Pedidos", "NewOrder", "Orders")</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Registros <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Empleados", "Index", "Employees")</li>
                                    <li>@Html.ActionLink("Proveedores", "Index", "Suppliers")</li>
                                    <li>@Html.ActionLink("Clientes", "Index", "Customers")</li>
                                    <li>@Html.ActionLink("Productos", "Index", "Products")</li>
                                    <li>@Html.ActionLink("Tipos de Documentos", "Index", "DocumentTypes")</li>
                                </ul>
                            </li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </nav>

        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProyectoFinalCerveceria/Views/Shared/_MarketPartial.cshtml
<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading">Quienes <span class="text-muted">Somos</span></h2>
        <p class="lead" style="text-align:justify;">Cerveceros artesanales independientes y radicados en el Ecuador, que hemos buscado a través de la unión, una mayor promoción y representatividad en el Ecuador y el mundo. Buscamos promover la cerveza artesanal ecuatoriana de calidad y un desarrollo sostenido de este nuevo sector productivo.</p>
    </div>
    <div class="col-md-5">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image" src="~/img/market-1.jpg">
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7 col-md-push-5">
        <h2 class="featurette-heading">Misión </h2>
        <p class="lead" style="text-align:justify;">Promover la cultura cervecera artesanal en el Ecuador, brindar un producto de alta calidad, y sabor; cuidando al máximo la calidad de nuestras materias primas. Alcanzando a la vez, los niveles de rentabilidad establecidos.</p>
    </div>
    <div class="col-md-5 col-md-pull-7">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image" src="~/img/market-2.jpg">
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading">Visión </h2>
        <p class="lead" style="text-align:justify;">Posicionarnos en el mercado internacional como un país líder en producción y consumo de cerveza artesanal local, y así convertirnos en un referente para productores de distintos países.</p>
    </div>
    <div class="col-md-5">
        <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image" src="~/img/market-3.jpg">
    </div>
</div>

<hr class="featurette-divider">

ProyectoFinalCerveceria/Views/Shared/_ServicePartial.cshtml
<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-lg-4">
            <img class="img-circle" src="~/img/circle-1.jpg" alt="Generic placeholder image" width="140" height="140">
            <h2>Somos</h2>
            <p>Cerveceros Artesanales independientes. Buscamos promover la Cerveza Artesanal Ecuatoriana de calidad y un desarrollo sostenido de este nuevo sector productivo.”</p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img-circle" src="~/img/circle-2.jpg" alt="Generic placeholder image" width="140" height="140">
            <h2>Descubre</h2>
            <p>Descubre nuevas sensaciones con la cerveza artesanal! Encuentra tus estilos favoritos, vive la revolución cervecera en Ecuador.</p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img-circle" src="~/img/circle-3.jpg" alt="Generic placeholder image" width="140" height="140">
            <h2>Cerveza Artesanal</h2>
            <p>Producto de calidad con sed de expansión; recetas tradicionales e innovadoras en calidad, sabor y textura; y premiadas internacionalmente.</p>
        </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
</div>